build: false
shallow_clone: false
clone_folder: C:\projects\ascii
branches:
  except:
    - gh-pages

install:
  - cinst -y php --version "8.3.30" --params "/InstallDir:C:\tools\php83"
  - cd C:\tools\php83
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - SET PATH=C:\tools\php83;%PATH%
  - cd C:\projects\ascii
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install --prefer-dist --no-interaction
  - php composer.phar dump-autoload -o

test_script:
  - cd C:\projects\ascii
  - php.exe --version
  - dir
  - php.exe vendor\bin\phpunit -c phpunit.xml
