build: false
shallow_clone: false
image: Visual Studio 2022
platform: x64
clone_folder: C:\projects\ascii

branches:
  except:
    - gh-pages

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - choco install -y php --version "8.3.30"
  - cd C:\tools\php83
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - SET PATH=C:\tools\php83;%PATH%
  - cd C:\projects\ascii
  - ps: >-
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
      Invoke-WebRequest https://getcomposer.org/installer -OutFile composer-setup.php
  - php composer-setup.php
  - del composer-setup.php
  - php composer.phar clear-cache
  - php composer.phar install --prefer-dist --no-interaction
  - php composer.phar dump-autoload -o

test_script:
  - cd C:\projects\ascii
  - php.exe --version
  - dir
  - php.exe vendor\bin\phpunit -c phpunit.xml
